spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:5}
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:1}
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.lionthanflower: DEBUG
app:
  staff-session:
    cookie-secure: false